import type { ProductPackage } from "@/lib/shared/contracts";

export type ProductPackageSource = Omit<ProductPackage, "sources" | "evidence"> & {
  sources: Array<Omit<ProductPackage["sources"][number], "sha256">>;
  evidence: Array<Omit<ProductPackage["evidence"][number], "assetSha256"> & {
    asset: { kind: "pdf-page"; page: number; sourcePath: string } | { kind: "copy"; sourcePath: string };
  }>;
};

const manual = "owner-manual";
const manualAsset = (page: number) => ({
  kind: "pdf-page" as const,
  page,
  sourcePath: "files/owner-manual.pdf",
});

const frontParts = [
  ["front-home-button", "Home Button", "control", "front_panel_home_button"],
  ["front-back-button", "Back Button", "control", "front_panel_back_button"],
  ["front-control-knob", "Control Knob", "control", "front_panel_control_knob"],
  ["front-left-knob", "Left Knob", "control", "front_panel_left_knob"],
  ["front-lcd-display", "LCD Display", "control", "front_panel_lcd_display"],
  ["front-right-knob", "Right Knob", "control", "front_panel_right_knob"],
  ["front-power-switch", "Power Switch", "control", "front_panel_power_switch"],
  ["front-storage-compartment", "Storage Compartment", "component", "front_panel_storage_compartment"],
  ["front-mig-spool-gun-cable-socket", "MIG Gun / Spool Gun Cable Socket", "connection", "front_panel_mig_spool_gun_cable_socket"],
  ["front-spool-gun-gas-outlet", "Spool Gun Gas Outlet", "connection", "front_panel_spool_gun_gas_outlet"],
  ["front-negative-socket", "Negative Socket", "connection", "front_panel_negative_socket"],
  ["front-positive-socket", "Positive Socket", "connection", "front_panel_positive_socket"],
  ["front-wire-feed-power-cable", "Wire Feed Power Cable", "connection", "front_panel_wire_feed_power_cable"],
] as const;

export const productPackageSource: ProductPackageSource = {
  schemaVersion: 1,
  packageVersion: "1.0.0",
  generatedAt: "2026-08-19T00:00:00.000Z",
  compiler: {
    name: "omnipro-product-compiler",
    version: "1.0.0",
  },
  product: {
    id: "vulcan-omnipro-220",
    name: "Vulcan OmniPro 220",
    description: "Evidence-grounded support package for the Vulcan OmniPro 220 multiprocess welder.",
  },
  sources: [
    {
      id: manual,
      title: "Vulcan OmniPro 220 Owner's Manual",
      path: "files/owner-manual.pdf",
      mediaType: "application/pdf",
      pageCount: 48,
      authority: "source-exact",
    },
    {
      id: "quick-start-guide",
      title: "Vulcan OmniPro 220 Quick Start Guide",
      path: "files/quick-start-guide.pdf",
      mediaType: "application/pdf",
      pageCount: 2,
      authority: "source-exact",
    },
    {
      id: "selection-chart",
      title: "Vulcan OmniPro 220 Welding Process Selection Chart",
      path: "files/selection-chart.pdf",
      mediaType: "application/pdf",
      pageCount: 1,
      authority: "source-exact",
    },
    {
      id: "product-front-photo",
      title: "Vulcan OmniPro 220 Product Photograph",
      path: "files/product.webp",
      mediaType: "image/webp",
      authority: "source-exact",
    },
    {
      id: "product-inside-photo",
      title: "Vulcan OmniPro 220 Inside Panel Photograph",
      path: "files/product-inside.webp",
      mediaType: "image/webp",
      authority: "source-exact",
    },
  ],
  evidence: [
    {
      id: "ev-front-controls-p8",
      sourceId: manual,
      parserPageIndex: 7,
      pageLabel: "8",
      title: "Front panel controls and connections",
      excerpt: "Front Panel Controls: Home Button, Back Button, Control Knob, LCD Display, Power Switch, MIG Gun / Spool Gun Cable Socket, Spool Gun Gas Outlet, Negative Socket, Positive Socket, and Wire Feed Power Cable.",
      bounds: { x: 0.03, y: 0.08, width: 0.94, height: 0.78 },
      publicAsset: "/products/omnipro-220/v1/pages/owner-manual-p8.webp",
      authority: "source-exact",
      supports: ["front panel names", "front panel layout", "semantic scene bindings"],
      asset: manualAsset(8),
    },
    {
      id: "ev-flux-dcen-p13",
      sourceId: manual,
      parserPageIndex: 12,
      pageLabel: "13",
      title: "Self-shielded flux-core DCEN polarity",
      excerpt: "Plug Ground Clamp Cable into Positive (+) Socket. Plug Wire Feed Power Cable into Negative (-) Socket.",
      bounds: { x: 0.03, y: 0.53, width: 0.94, height: 0.42 },
      publicAsset: "/products/omnipro-220/v1/pages/owner-manual-p13.webp",
      authority: "source-exact",
      supports: ["DCEN polarity", "flux-core cable placement", "connector seating warning"],
      asset: manualAsset(13),
    },
    {
      id: "ev-mig-dcep-p14",
      sourceId: manual,
      parserPageIndex: 13,
      pageLabel: "14",
      title: "Gas-shielded solid-core DCEP polarity",
      excerpt: "Plug Ground Clamp Cable into Negative (-) Socket. Plug Wire Feed Power Cable into Positive (+) Socket.",
      bounds: { x: 0.03, y: 0.04, width: 0.94, height: 0.5 },
      publicAsset: "/products/omnipro-220/v1/pages/owner-manual-p14.webp",
      authority: "source-exact",
      supports: ["DCEP polarity", "MIG cable placement", "shielding gas setup"],
      asset: manualAsset(14),
    },
    {
      id: "ev-duty-cycle-p19",
      sourceId: manual,
      parserPageIndex: 18,
      pageLabel: "19",
      title: "MIG duty-cycle ratings",
      excerpt: "240 VAC: 25% use at 200 A, 2-1/2 minutes welding and 7-1/2 minutes resting in a ten-minute period.",
      bounds: { x: 0.02, y: 0.03, width: 0.96, height: 0.5 },
      publicAsset: "/products/omnipro-220/v1/pages/owner-manual-p19.webp",
      authority: "source-exact",
      supports: ["duty-cycle definition", "200 A 240 V rating", "thermal protection behavior"],
      asset: manualAsset(19),
    },
    {
      id: "ev-tig-connections-p24",
      sourceId: manual,
      parserPageIndex: 23,
      pageLabel: "24",
      title: "TIG cable and optional foot-pedal setup",
      excerpt: "Plug Ground Clamp Cable into Positive Socket. Plug TIG Torch Cable into Negative Socket. The foot pedal is sold separately.",
      bounds: { x: 0.03, y: 0.19, width: 0.94, height: 0.75 },
      publicAsset: "/products/omnipro-220/v1/pages/owner-manual-p24.webp",
      authority: "source-exact",
      supports: ["TIG polarity", "TIG cable placement", "optional foot pedal", "setup safety warning"],
      asset: manualAsset(24),
    },
    {
      id: "ev-tig-argon-p25",
      sourceId: manual,
      parserPageIndex: 24,
      pageLabel: "25",
      title: "TIG shielding-gas setup",
      excerpt: "Place a 100% Argon cylinder near the welder, secure it with two straps, and connect the TIG torch shielding gas hose to the regulator outlet.",
      bounds: { x: 0.02, y: 0.02, width: 0.96, height: 0.48 },
      publicAsset: "/products/omnipro-220/v1/pages/owner-manual-p25.webp",
      authority: "source-exact",
      supports: ["100% argon requirement", "cylinder restraint", "TIG gas hose connection"],
      asset: manualAsset(25),
    },
    {
      id: "ev-wire-porosity-p37",
      sourceId: manual,
      parserPageIndex: 36,
      pageLabel: "37",
      title: "Wire-weld porosity diagnosis",
      excerpt: "Possible causes include incorrect polarity, MIG shielding-gas problems, dirty workpiece or wire, inconsistent travel speed, and excessive contact-tip-to-work distance.",
      bounds: { x: 0.02, y: 0.03, width: 0.49, height: 0.55 },
      publicAsset: "/products/omnipro-220/v1/pages/owner-manual-p37.webp",
      authority: "source-exact",
      supports: ["porosity appearance", "ordered porosity causes", "process-specific gas checks"],
      asset: manualAsset(37),
    },
    {
      id: "ev-selection-chart",
      sourceId: "selection-chart",
      parserPageIndex: 0,
      pageLabel: "1",
      title: "Visual-only welding process selection chart",
      bounds: { x: 0, y: 0, width: 1, height: 1 },
      publicAsset: "/products/omnipro-220/v1/figures/selection-chart.webp",
      authority: "source-exact",
      supports: ["visual process selection", "material and thickness settings", "visual-only evidence retrieval"],
      asset: { kind: "pdf-page", page: 1, sourcePath: "files/selection-chart.pdf" },
    },
    {
      id: "ev-product-front",
      sourceId: "product-front-photo",
      title: "Official product front photograph",
      bounds: { x: 0, y: 0, width: 1, height: 1 },
      publicAsset: "/products/omnipro-220/v1/figures/product-front.webp",
      authority: "source-exact",
      supports: ["exterior appearance", "front panel placement", "reconstruction comparison"],
      asset: { kind: "copy", sourcePath: "files/product.webp" },
    },
    {
      id: "ev-product-inside",
      sourceId: "product-inside-photo",
      title: "Official inside-panel photograph",
      bounds: { x: 0, y: 0, width: 1, height: 1 },
      publicAsset: "/products/omnipro-220/v1/figures/product-inside.webp",
      authority: "source-exact",
      supports: ["wire feed mechanism appearance", "inside-panel component placement"],
      asset: { kind: "copy", sourcePath: "files/product-inside.webp" },
    },
  ],
  entities: [
    ...frontParts.map(([id, name, category]) => ({
      id,
      name,
      category,
      description: `Documented ${name.toLowerCase()} on the OmniPro 220 front panel. Its behavior depends on the selected welding process and control-screen context.`,
      aliases: [],
      evidenceIds: ["ev-front-controls-p8", "ev-product-front"],
      sceneBindingId: `binding-${id}`,
    })),
    {
      id: "tig-torch",
      name: "TIG Torch",
      category: "component",
      description: "Optional TIG torch connected to the negative socket for the manual's DC TIG setup.",
      aliases: ["torch"],
      evidenceIds: ["ev-tig-connections-p24"],
    },
    {
      id: "ground-clamp",
      name: "Ground Clamp Cable",
      category: "connection",
      description: "Work lead whose required socket depends on the selected process and polarity.",
      aliases: ["work clamp", "ground"],
      evidenceIds: ["ev-flux-dcen-p13", "ev-mig-dcep-p14", "ev-tig-connections-p24"],
    },
    {
      id: "argon-cylinder",
      name: "100% Argon Cylinder",
      category: "consumable",
      description: "Shielding gas source required by the manual's TIG setup.",
      aliases: ["argon", "shielding gas"],
      evidenceIds: ["ev-tig-argon-p25"],
    },
  ],
  facts: [
    {
      id: "fact-mig-240v-200a-duty",
      statement: "At 240 V and 200 A, the published MIG duty cycle is 25% within a ten-minute period.",
      value: { value: 25, unit: "percent" },
      entityIds: [],
      conditions: { process: "mig", inputVoltage: 240, amperage: 200 },
      status: "verified",
      evidenceIds: ["ev-duty-cycle-p19"],
      tags: ["duty-cycle", "mig", "240v"],
    },
    {
      id: "fact-mig-240v-200a-work-time",
      statement: "A 25% duty cycle means 2.5 minutes welding and 7.5 minutes resting in a ten-minute period.",
      value: "2.5 minutes welding; 7.5 minutes resting",
      entityIds: [],
      conditions: { process: "mig", inputVoltage: 240, amperage: 200 },
      status: "verified",
      evidenceIds: ["ev-duty-cycle-p19"],
      tags: ["duty-cycle", "duration"],
    },
    {
      id: "fact-flux-dcen",
      statement: "Self-shielded flux-core welding uses DCEN: wire feed power cable negative and ground clamp positive.",
      value: "DCEN",
      entityIds: ["front-negative-socket", "front-positive-socket", "front-wire-feed-power-cable", "ground-clamp"],
      conditions: { process: "flux-core", shielding: "self-shielded" },
      status: "verified",
      evidenceIds: ["ev-flux-dcen-p13"],
      tags: ["polarity", "flux-core", "connection"],
    },
    {
      id: "fact-mig-dcep",
      statement: "Gas-shielded solid-core MIG welding uses DCEP: wire feed power cable positive and ground clamp negative.",
      value: "DCEP",
      entityIds: ["front-negative-socket", "front-positive-socket", "front-wire-feed-power-cable", "ground-clamp"],
      conditions: { process: "mig", shielding: "gas-shielded" },
      status: "verified",
      evidenceIds: ["ev-mig-dcep-p14"],
      tags: ["polarity", "mig", "connection"],
    },
    {
      id: "fact-tig-connections",
      statement: "For the documented TIG setup, connect the TIG torch cable to negative and the ground clamp cable to positive.",
      value: "torch negative; ground positive",
      entityIds: ["tig-torch", "ground-clamp", "front-negative-socket", "front-positive-socket"],
      conditions: { process: "tig" },
      status: "verified",
      evidenceIds: ["ev-tig-connections-p24"],
      tags: ["polarity", "tig", "connection"],
    },
    {
      id: "fact-tig-argon",
      statement: "The documented TIG setup requires a 100% argon shielding-gas cylinder.",
      value: "100% argon",
      entityIds: ["argon-cylinder", "tig-torch"],
      conditions: { process: "tig" },
      status: "verified",
      evidenceIds: ["ev-tig-argon-p25"],
      tags: ["tig", "shielding-gas"],
    },
    {
      id: "fact-tig-foot-pedal-optional",
      statement: "The TIG foot pedal is optional and sold separately.",
      value: true,
      entityIds: [],
      conditions: { process: "tig" },
      status: "verified",
      evidenceIds: ["ev-tig-connections-p24"],
      tags: ["tig", "foot-pedal"],
    },
    {
      id: "fact-wire-porosity-causes",
      statement: "Wire-weld porosity checks include polarity, MIG shielding gas, contamination, travel consistency, and contact-tip-to-work distance.",
      value: "polarity; shielding gas for MIG; cleanliness; travel speed; CTWD",
      entityIds: [],
      conditions: { symptom: "porosity" },
      status: "verified",
      evidenceIds: ["ev-wire-porosity-p37"],
      tags: ["diagnosis", "porosity", "wire-weld"],
    },
  ],
  procedures: [
    {
      id: "procedure-tig-setup",
      title: "TIG setup",
      summary: "Safely connect the TIG torch, work lead, optional foot pedal, and 100% argon shielding gas.",
      process: "tig",
      prerequisites: ["Welder is off and unplugged", "Work area has ventilation and space around the welder"],
      evidenceIds: ["ev-tig-connections-p24", "ev-tig-argon-p25"],
      steps: [
        {
          id: "tig-safe-power-off",
          title: "Power down before setup",
          instruction: "Turn the power switch off and unplug the welder before changing connections.",
          warning: "Accidental operation can cause serious injury.",
          evidenceIds: ["ev-tig-connections-p24"],
          sceneCommands: [{ type: "focus-part", entityId: "front-power-switch" }, { type: "highlight-part", entityId: "front-power-switch", emphasis: "warning" }],
          requiresConfirmation: true,
        },
        {
          id: "tig-ground-positive",
          title: "Connect the ground clamp",
          instruction: "Plug the ground clamp cable into the positive socket and twist clockwise fully to lock.",
          evidenceIds: ["ev-tig-connections-p24"],
          sceneCommands: [{ type: "focus-part", entityId: "front-positive-socket" }, { type: "animate-connection", fromEntityId: "ground-clamp", toEntityId: "front-positive-socket" }],
          proposedTwinPatch: { process: "tig", groundConnection: "positive" },
          requiresConfirmation: true,
        },
        {
          id: "tig-torch-negative",
          title: "Connect the TIG torch",
          instruction: "Plug the TIG torch cable into the negative socket and twist clockwise fully to lock.",
          evidenceIds: ["ev-tig-connections-p24"],
          sceneCommands: [{ type: "focus-part", entityId: "front-negative-socket" }, { type: "animate-connection", fromEntityId: "tig-torch", toEntityId: "front-negative-socket" }],
          proposedTwinPatch: { torchConnection: "negative" },
          requiresConfirmation: true,
        },
        {
          id: "tig-foot-pedal",
          title: "Connect the optional foot pedal",
          instruction: "If using the optional foot pedal, connect its cable to the foot-pedal socket inside the welder and secure the collar.",
          evidenceIds: ["ev-tig-connections-p24"],
          sceneCommands: [],
          requiresConfirmation: false,
        },
        {
          id: "tig-secure-argon",
          title: "Secure the argon cylinder",
          instruction: "Place a 100% argon cylinder near the welder and secure it with two straps before opening or connecting it.",
          warning: "Stand to the side of the valve opening when briefly clearing the valve.",
          evidenceIds: ["ev-tig-argon-p25"],
          sceneCommands: [],
          proposedTwinPatch: { shieldingGas: "100% argon" },
          requiresConfirmation: true,
        },
        {
          id: "tig-connect-gas",
          title: "Connect shielding gas",
          instruction: "Attach the TIG torch shielding-gas hose to the regulator outlet and wrench-tighten the connection.",
          evidenceIds: ["ev-tig-argon-p25"],
          sceneCommands: [],
          requiresConfirmation: true,
        },
      ],
    },
    {
      id: "procedure-mig-polarity",
      title: "Gas-shielded solid-core MIG polarity",
      summary: "Configure DCEP for gas-shielded solid-core wire welding.",
      process: "mig",
      prerequisites: ["Welder is off and unplugged", "Solid-core wire and shielding gas are being used"],
      evidenceIds: ["ev-mig-dcep-p14"],
      steps: [
        {
          id: "mig-ground-negative",
          title: "Ground clamp to negative",
          instruction: "Plug the ground clamp cable into the negative socket and lock it clockwise.",
          evidenceIds: ["ev-mig-dcep-p14"],
          sceneCommands: [{ type: "animate-connection", fromEntityId: "ground-clamp", toEntityId: "front-negative-socket" }],
          proposedTwinPatch: { process: "mig", groundConnection: "negative" },
          requiresConfirmation: true,
        },
        {
          id: "mig-wire-positive",
          title: "Wire feed power to positive",
          instruction: "Plug the wire feed power cable into the positive socket and lock it clockwise.",
          evidenceIds: ["ev-mig-dcep-p14"],
          sceneCommands: [{ type: "animate-connection", fromEntityId: "front-wire-feed-power-cable", toEntityId: "front-positive-socket" }],
          proposedTwinPatch: { torchConnection: "positive" },
          requiresConfirmation: true,
        },
      ],
    },
    {
      id: "procedure-flux-polarity",
      title: "Self-shielded flux-core polarity",
      summary: "Configure DCEN for self-shielded gasless flux-core wire welding.",
      process: "flux-core",
      prerequisites: ["Welder is off and unplugged", "Self-shielded flux-core wire is being used"],
      evidenceIds: ["ev-flux-dcen-p13"],
      steps: [
        {
          id: "flux-ground-positive",
          title: "Ground clamp to positive",
          instruction: "Plug the ground clamp cable into the positive socket and lock it clockwise.",
          evidenceIds: ["ev-flux-dcen-p13"],
          sceneCommands: [{ type: "animate-connection", fromEntityId: "ground-clamp", toEntityId: "front-positive-socket" }],
          proposedTwinPatch: { process: "flux-core", groundConnection: "positive" },
          requiresConfirmation: true,
        },
        {
          id: "flux-wire-negative",
          title: "Wire feed power to negative",
          instruction: "Plug the wire feed power cable into the negative socket and lock it clockwise.",
          evidenceIds: ["ev-flux-dcen-p13"],
          sceneCommands: [{ type: "animate-connection", fromEntityId: "front-wire-feed-power-cable", toEntityId: "front-negative-socket" }],
          proposedTwinPatch: { torchConnection: "negative" },
          requiresConfirmation: true,
        },
      ],
    },
  ],
  troubleshootingPaths: [
    {
      id: "troubleshoot-wire-porosity",
      symptom: "wire-weld porosity",
      summary: "Process-aware porosity checks ordered from setup to technique.",
      startNodeId: "porosity-process",
      nodes: [
        { id: "porosity-process", kind: "question", text: "Are you using gas-shielded MIG or self-shielded flux-core?", evidenceIds: ["ev-wire-porosity-p37"], next: { mig: "porosity-polarity", "flux-core": "porosity-polarity" } },
        { id: "porosity-polarity", kind: "check", text: "Verify the polarity for the selected process before changing technique.", evidenceIds: ["ev-wire-porosity-p37", "ev-mig-dcep-p14", "ev-flux-dcen-p13"], next: { correct: "porosity-gas", incorrect: "porosity-fix-polarity" } },
        { id: "porosity-fix-polarity", kind: "resolution", text: "Correct the polarity, then make a test weld on clean scrap.", evidenceIds: ["ev-wire-porosity-p37"], next: {} },
        { id: "porosity-gas", kind: "question", text: "If using MIG, is shielding gas flowing and is the nozzle clean? Skip this gas check for self-shielded flux-core.", evidenceIds: ["ev-wire-porosity-p37"], next: { yes: "porosity-cleanliness", no: "porosity-fix-gas", skip: "porosity-cleanliness" } },
        { id: "porosity-fix-gas", kind: "resolution", text: "Restore the wire supplier's recommended shielding gas, clean the nozzle, and maintain proper CTWD.", evidenceIds: ["ev-wire-porosity-p37"], next: {} },
        { id: "porosity-cleanliness", kind: "check", text: "Clean the workpiece to bare metal and verify the wire has no oil, coating, or residue.", evidenceIds: ["ev-wire-porosity-p37"], next: { clean: "porosity-technique", dirty: "porosity-fix-cleanliness" } },
        { id: "porosity-fix-cleanliness", kind: "resolution", text: "Clean the workpiece and wire, then repeat the test weld.", evidenceIds: ["ev-wire-porosity-p37"], next: {} },
        { id: "porosity-technique", kind: "check", text: "Maintain steady travel speed and reduce excessive contact-tip-to-work distance.", evidenceIds: ["ev-wire-porosity-p37"], next: { resolved: "porosity-resolved", persists: "porosity-escalate" } },
        { id: "porosity-resolved", kind: "resolution", text: "The source-backed setup and technique checks are complete.", evidenceIds: ["ev-wire-porosity-p37"], next: {} },
        { id: "porosity-escalate", kind: "resolution", text: "Stop and inspect consumables, connections, and machine condition before continuing. Seek qualified help if the problem persists.", evidenceIds: ["ev-wire-porosity-p37"], next: {} },
      ],
    },
  ],
  sceneBindings: frontParts.map(([id, , , meshName]) => ({
    id: `binding-${id}`,
    entityId: id,
    meshNames: [meshName],
    evidenceIds: ["ev-front-controls-p8", "ev-product-front"],
    authority: "verified-reconstruction" as const,
  })),
  acceptanceCases: [
    {
      id: "case-tig-setup",
      journey: "TIG setup",
      prompt: "How do I connect everything for TIG welding?",
      expectedEvidenceIds: ["ev-tig-connections-p24", "ev-tig-argon-p25"],
      expectedFactIds: ["fact-tig-connections", "fact-tig-argon", "fact-tig-foot-pedal-optional"],
      expectedProcedureId: "procedure-tig-setup",
      expectedClarificationFields: [],
      requiredPhrases: ["negative", "positive", "100% argon"],
    },
    {
      id: "case-flux-polarity",
      journey: "Flux-core polarity",
      prompt: "Which sockets for self-shielded flux core?",
      expectedEvidenceIds: ["ev-flux-dcen-p13"],
      expectedFactIds: ["fact-flux-dcen"],
      expectedProcedureId: "procedure-flux-polarity",
      expectedClarificationFields: [],
      requiredPhrases: ["DCEN", "positive", "negative"],
    },
    {
      id: "case-mig-polarity",
      journey: "MIG polarity",
      prompt: "Which polarity for gas-shielded solid wire MIG?",
      expectedEvidenceIds: ["ev-mig-dcep-p14"],
      expectedFactIds: ["fact-mig-dcep"],
      expectedProcedureId: "procedure-mig-polarity",
      expectedClarificationFields: [],
      requiredPhrases: ["DCEP", "positive", "negative"],
    },
    {
      id: "case-duty-cycle",
      journey: "Duty-cycle planning",
      prompt: "What's the duty cycle for MIG welding at 200A on 240V?",
      expectedEvidenceIds: ["ev-duty-cycle-p19"],
      expectedFactIds: ["fact-mig-240v-200a-duty", "fact-mig-240v-200a-work-time"],
      expectedClarificationFields: [],
      requiredPhrases: ["25%", "2.5 minutes", "7.5 minutes"],
    },
    {
      id: "case-porosity",
      journey: "Porosity diagnosis",
      prompt: "I'm getting porosity in my flux-cored welds. What should I check?",
      expectedEvidenceIds: ["ev-wire-porosity-p37", "ev-flux-dcen-p13"],
      expectedFactIds: ["fact-wire-porosity-causes", "fact-flux-dcen"],
      expectedClarificationFields: [],
      requiredPhrases: ["polarity", "clean", "travel", "CTWD"],
    },
    {
      id: "case-ambiguous-settings",
      journey: "Ambiguous settings request",
      prompt: "What settings should I use for 1/8-inch steel?",
      expectedEvidenceIds: ["ev-selection-chart"],
      expectedFactIds: [],
      expectedClarificationFields: ["process", "inputVoltage", "wireOrElectrode", "shieldingGas"],
      requiredPhrases: [],
    },
    {
      id: "case-visual-chart",
      journey: "Visual-only evidence retrieval",
      prompt: "Show me the process selection chart.",
      expectedEvidenceIds: ["ev-selection-chart"],
      expectedFactIds: [],
      expectedClarificationFields: [],
      requiredPhrases: ["selection chart"],
    },
    {
      id: "case-click-explain",
      journey: "Click to explain",
      prompt: "What is the negative socket?",
      expectedEvidenceIds: ["ev-front-controls-p8"],
      expectedFactIds: [],
      expectedClarificationFields: [],
      requiredPhrases: ["Negative Socket"],
    },
  ],
};
